const Mock = require('mockjs')

const proxy = {
  'POST /login/withpassword': Mock.mock({
    code: 200,
    retMsg: '调用成功',
    data: {
      token: 'AAA',
      routes: [{
        name: '首页',
        icon: 'smile',
        path: '/home',
        key: '/home',
        exact: true,
        routes: [],
        children: [],
        parentKeys: [
          '/',
        ],
      }, {
        name: '示例展示',
        icon: 'menu',
        hideInMenu: false,
        path: '/data',
        key: '/data',
        exact: true,
        routes: [{
          name: '图表展示',
          path: '/data/echart',
          icon: 'smile',
          key: '/data/analysis',
          exact: true,
          routes: null,
        }, {
          name: '表格展示',
          path: '/data/table',
          icon: 'smile',
          key: '/data/monitor',
          exact: true,
          routes: null,
        }, {
          name: '表单展示',
          path: '/data/from',
          icon: 'user',
          key: '/data/from',
          exact: true,
          routes: null,
        }],
      }, {
        name: '权限管理',
        icon: 'menu',
        hideInMenu: false,
        path: '/auth',
        key: '/auth',
        exact: true,
        routes: [{
          name: '用户管理',
          path: '/auth/user',
          icon: 'smile',
          key: '/auth/user',
          exact: true,
          routes: null,
        }, {
          name: '角色管理',
          path: '/auth/rules',
          icon: 'smile',
          key: '/auth/rules',
          exact: true,
          routes: null,
        }, {
          name: '菜单管理',
          path: '/auth/menu',
          icon: 'user',
          key: '/auth/menu',
          exact: true,
          routes: null,
        }],
      }, {
        name: '个人设置',
        path: '/user/setting',
        icon: 'setting',
        key: '/user/setting',
        exact: true,
        routes: null,
      }, {
        path: 'https://www.baidu.com',
        name: '跳转外站',
        key: '/my',
        icon: 'pushpin',
        exact: true,
        routes: null,
        parentKeys: [
          '/',
        ],
      }],
    },
  }),
  'POST /login/withtoken': Mock.mock({
    code: 200,
    retMsg: '调用成功',
    data: {
      token: 'AAA',
      routes: [{
        name: '首页',
        icon: 'smile',
        path: '/home',
        key: '/home',
        exact: true,
        routes: [],
      }, {
        name: '示例展示',
        icon: 'menu',
        hideInMenu: false,
        path: '/data',
        key: '/data',
        exact: true,
        routes: [{
          name: '图表展示',
          path: '/data/echart',
          icon: 'smile',
          key: '/data/analysis',
          exact: true,
          routes: null,
        }, {
          name: '表格展示',
          path: '/data/table',
          icon: 'smile',
          key: '/data/monitor',
          exact: true,
          routes: null,
        }, {
          name: '表单展示',
          path: '/data/from',
          icon: 'user',
          key: '/data/from',
          exact: true,
          routes: null,
        }],
      }, {
        name: '权限管理',
        icon: 'menu',
        hideInMenu: false,
        path: '/auth',
        key: '/auth',
        routes: [{
          name: '用户管理',
          path: '/auth/user',
          icon: 'smile',
          key: '/auth/user',
          exact: true,
          routes: null,
        }, {
          name: '角色管理',
          path: '/auth/rules',
          icon: 'smile',
          key: '/auth/rules',
          exact: true,
          routes: null,
        }, {
          name: '菜单管理',
          path: '/auth/menu',
          icon: 'user',
          key: '/auth/menu',
          exact: true,
          routes: null,
        }],
      }, {
        name: '个人设置',
        path: '/user/setting',
        icon: 'setting',
        key: '/user/setting',
        exact: true,
        routes: null,
      }, {
        path: 'https://www.baidu.com',
        name: '跳转外站',
        key: '/my',
        icon: 'pushpin',
        exact: true,
        routes: null,
        parentKeys: [
          '/',
        ],
      }],
    },
  }),
  'POST /user/getuserlist': Mock.mock({
    code: 200,
    retMsg: '调用成功',
    data: {
      total: 13, // 总条数
      'data|13': [
        {
          'id|+1': 10,
          'key|+1': 0,
          username: '周飞',
          nickname: '周飞',
          avatar: '/assets/img/avatar.png',
          email: 'yaoyingzhe-jk',
          loginfailure: 0,
          logintime: '2020-02-10 10:20:12',
          createtime: '2020-02-10 10:20:12',
          updatetime: '2020-02-10 10:20:12',
          status: 'normal',
          groups: '6',
          groups_text: 'dsp规则组',
        },
      ],
    },
  }),
}
module.exports = proxy
